# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDeck < Formula
  desc "The TweetDeck for Claude Code. A Zellij sidebar plugin for managing multiple Claude Code sessions."
  homepage "https://cc-deck.github.io"
  version "0.2.1-rc.2"
  license "Apache-2.0"

  depends_on "zellij" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.2/cc-deck_0.2.1-rc.2_darwin_amd64.tar.gz"
      sha256 "c78b960b4ceb35a57f828109f7b8a159529f7714d348168045c997d58d8a93f6"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.2/cc-deck_0.2.1-rc.2_darwin_arm64.tar.gz"
      sha256 "c750653a060f1378ced0905a76a336895fab8c2dd629d54e65447bf3dbc0dd67"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.2/cc-deck_0.2.1-rc.2_linux_amd64.tar.gz"
      sha256 "60b02e0c98a86a5ae8394c04cad4817351eb0ba304e802606cd2fb4d4329fa41"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.2/cc-deck_0.2.1-rc.2_linux_arm64.tar.gz"
      sha256 "055195d9f938ec77cbb5fc72082fb5fac7eb69ecf27e3b62f00145a7efc51408"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, set up the Zellij plugin and hooks:

        cc-deck plugin install

      Then start Zellij with the cc-deck layout:

        zellij --layout cc-deck

      Zellij is recommended but not required (cc-deck also works inside containers).
    EOS
  end
end
