# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDeck < Formula
  desc "The TweetDeck for Claude Code. A Zellij sidebar plugin for managing multiple Claude Code sessions."
  homepage "https://cc-deck.github.io"
  version "0.3.0"
  license "Apache-2.0"

  depends_on "zellij" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.3.0/cc-deck_0.3.0_darwin_amd64.tar.gz"
      sha256 "861bd721ee5d979302ba14c5d44d78f9a31955ccb8fc1ff454524735fdaeba0a"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.3.0/cc-deck_0.3.0_darwin_arm64.tar.gz"
      sha256 "0b5de541404ab03d517d1b7b0912904d640d2dce4c2be8e52da184a003b64625"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.3.0/cc-deck_0.3.0_linux_amd64.tar.gz"
      sha256 "44b295be0f6388a452329b90156951b1e8191bcae40eaf4649e122fec6b75193"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.3.0/cc-deck_0.3.0_linux_arm64.tar.gz"
      sha256 "fc5634e42930da7127baaf8e01287857f0e891214603ad4a4542160ba7e0693d"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, set up the Zellij plugin and hooks:

        cc-deck plugin install

      Then start Zellij with the cc-deck layout:

        zellij --layout cc-deck

      Zellij is recommended but not required (cc-deck also works inside containers).
    EOS
  end
end
