# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDeck < Formula
  desc "The TweetDeck for Claude Code. A Zellij sidebar plugin for managing multiple Claude Code sessions."
  homepage "https://cc-deck.github.io"
  version "0.2.1-rc.1"
  license "Apache-2.0"

  depends_on "zellij" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.1/cc-deck_0.2.1-rc.1_darwin_amd64.tar.gz"
      sha256 "03487bdbfd1c85553b12d422b47afae1d0db0c651c4da498cd96f2d3a22e9eb7"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.1/cc-deck_0.2.1-rc.1_darwin_arm64.tar.gz"
      sha256 "fd06192248cefab02577dbe31c3dc71b9db30f11ce50cb787dd0d91cc81a2db5"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.1/cc-deck_0.2.1-rc.1_linux_amd64.tar.gz"
      sha256 "5b16200283d07563651e0dd9ee97f1d9e621307f6aff20188c4d3436f79d52e5"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.2.1-rc.1/cc-deck_0.2.1-rc.1_linux_arm64.tar.gz"
      sha256 "d84d1231050f8c192df7854e1f1d65a1089092e1348440c3d65375a5dcfeeebf"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, set up the Zellij plugin and hooks:

        cc-deck plugin install

      Then start Zellij with the cc-deck layout:

        zellij --layout cc-deck

      Zellij is recommended but not required (cc-deck also works inside containers).
    EOS
  end
end
