# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDeck < Formula
  desc "The TweetDeck for Claude Code. A Zellij sidebar plugin for managing multiple Claude Code sessions."
  homepage "https://cc-deck.github.io"
  version "0.10.2"
  license "Apache-2.0"

  depends_on "zellij" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.10.2/cc-deck_0.10.2_darwin_amd64.tar.gz"
      sha256 "601a903fc0136d73011d3c623ba33e0b5df8ef11f39e0c045ab15739014b6fa9"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.10.2/cc-deck_0.10.2_darwin_arm64.tar.gz"
      sha256 "cba3671400143c04fb04b3145ac2757683acd3c285bef12a3464fdd31d07f548"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.10.2/cc-deck_0.10.2_linux_amd64.tar.gz"
      sha256 "d85b22839091fc69f321d17e67d3b67e7723889fbbe9fa6738e918366d145017"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.10.2/cc-deck_0.10.2_linux_arm64.tar.gz"
      sha256 "d5e5fb91478281e58bc4f0a94ce3f4f268b5cf173e6728a10da24bf8e5421c42"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, set up the Zellij plugin and hooks:

        cc-deck config plugin install

      Then start Zellij with the cc-deck layout:

        zellij --layout cc-deck

      Zellij is recommended but not required (cc-deck also works inside containers).
    EOS
  end
end
