# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDeck < Formula
  desc "The TweetDeck for Claude Code. A Zellij sidebar plugin for managing multiple Claude Code sessions."
  homepage "https://cc-deck.github.io"
  version "0.12.0"
  license "Apache-2.0"

  depends_on "zellij" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.12.0/cc-deck_0.12.0_darwin_amd64.tar.gz"
      sha256 "f9929cbf681bd77c776aa966a74d0f902658e037ecc7e0d00d5ae7705f201ca4"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.12.0/cc-deck_0.12.0_darwin_arm64.tar.gz"
      sha256 "4b6d25f29026f383d1ef04de3617b3ad50f03634b77d37e744ed1efdbdb8d090"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.12.0/cc-deck_0.12.0_linux_amd64.tar.gz"
      sha256 "8cbee850c400f471fb1b5e4cb0d0d17b20660556fcd8fe20aaf7860fbc15456f"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.12.0/cc-deck_0.12.0_linux_arm64.tar.gz"
      sha256 "0e9f10e572d78d04dd6b7081e0e7b7a9590cc37966b83d07eadc90ccafaf2139"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, set up the Zellij plugin and hooks:

        cc-deck config plugin install

      Then start Zellij with the cc-deck layout:

        zellij --layout cc-deck

      Zellij is recommended but not required (cc-deck also works inside containers).
    EOS
  end
end
