# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDeck < Formula
  desc "The TweetDeck for Claude Code. A Zellij sidebar plugin for managing multiple Claude Code sessions."
  homepage "https://cc-deck.github.io"
  version "0.13.0"
  license "Apache-2.0"

  depends_on "zellij" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.13.0/cc-deck_0.13.0_darwin_amd64.tar.gz"
      sha256 "90c41dc0a23041ae373beb3a05079d22f964ba04e7351a3f605b58a8ed351cf3"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.13.0/cc-deck_0.13.0_darwin_arm64.tar.gz"
      sha256 "a6b8f4bdd9876c603f850edb9439829c5c233e82727203c3d8c0c11464eb3873"

      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.13.0/cc-deck_0.13.0_linux_amd64.tar.gz"
      sha256 "f99f92b133773db43f2641f1bc262ac3658c8dd2c522d6e46ed12d4c616414a7"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cc-deck/cc-deck/releases/download/v0.13.0/cc-deck_0.13.0_linux_arm64.tar.gz"
      sha256 "e38152b0a865c363618cfd9a6b21976da7188cf8f823ce73568c05c990a2381f"
      define_method(:install) do
        bin.install "cc-deck"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, set up the Zellij plugin and hooks:

        cc-deck config plugin install

      Then start Zellij with the cc-deck layout:

        zellij --layout cc-deck

      Zellij is recommended but not required (cc-deck also works inside containers).
    EOS
  end
end
